name: Backend Tests

on:
  push:
    branches:
      - "master"
jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Execute unit tests
        run: dotnet test .\TestProject1\